### ISSUE TITLE
Confluent error message "Cannot read properties of undefined (reading 'environment')"

### ISSUE THREAD

**Issue by SmajlovicA** [electrolux-oss/infrawallet#123]
Hi team,

Anyone has issues when adding Confluent Cloud? I have key and secrets but I continue getting this error:

Cannot read properties of undefined (reading 'environment')

Thanks

**Comment by holiiveira** [comment]
Hi, can you confirm that your API key complies with [documentation](https://github.com/electrolux-oss/infrawallet/blob/main/docs/getting-started.md#confluent-cloud-integration) ?

The API key must be a service account, and the resource scope must be "cloud resource management".
