### ISSUE TITLE
[BUG] Cost data is wrongly mapped into Budget graphs

### ISSUE THREAD

**Issue by tollercode** [electrolux-oss/infrawallet#124]
### Current Situation

Having this cost data in November
![image](https://github.com/user-attachments/assets/8230dbed-7bc2-4084-b97b-f87f8e143de1)

The data is shown in the Budget Graphs in Januaray
![image](https://github.com/user-attachments/assets/96f997a1-e38e-4008-a940-06fb8f6d7ff7)

### Desired

Data of November should be shown in November also on Budget-Chart

**Comment by darylgraham** [comment]
I just debugged this screen myself. 

The cost data is passed into the BudgetChart component as an array of monthly costs here: https://github.com/electrolux-oss/infrawallet/blob/main/plugins/infrawallet/src/components/Budgets/Budgets.tsx#L250

```{
    "id": "AWS",
    "reports": {
        "2023-12": 19.6492511966,
        "2024-01": 1939.0336325847002,
        "2024-02": 1610.1251975480995,
        "2024-03": 2149.6599309432,
        "2024-04": 2629.0959797089004,
        "2024-05": 2603.6509832689,
        "2024-06": 2438.023622028399,
        "2024-07": 2767.510390127999,
        "2024-08": 9312.452064800302,
        "2024-09": 8760.504147668702,
        "2024-10": 10055.072295576203,
        "2024-11": 5529.263631147701
    }
}
```

It's then converted to a running sum here: https://github.com/electrolux-oss/infrawallet/blob/main/plugins/infrawallet/src/components/Budgets/Budgets.tsx#L91-L98
```
{
    0: 19.6492511966,
    1: 1958.6828837813002,
    2: 3568.8080813294,
    3: 5718.4680122726,
    4: 8347.5639919815,
    5: 10951.214975250401,
    6: 13389.2385972788,
    7: 16156.748987406798,
    8: 25469.2010522071,
    9: 34229.7051998758,
    10: 44284.77749545201,
    11: 49814.04112659971
}
```

This is then plotted on the chart, with a constant set of x-axis titles: https://github.com/electrolux-oss/infrawallet/blob/main/plugins/infrawallet/src/components/Budgets/Budgets.tsx#L122

```
xAxis={[
          {
            data: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            scaleType: 'band',
          },
        ]}
```

I think that the x-axis labels just need to be dynamically generated by mapping the keys from the original report variable to the month names.

**Comment by emillg** [comment]
@tollercode @darylgraham Can you check if version `0.2.0-20241118212048-4e21a4a` works for you?
