### ISSUE TITLE
enhancement: add default to group by

### ISSUE THREAD

**Issue by Alok650** [electrolux-oss/infrawallet#15]
Hi guys,
Is it possible to add a default group by i.e. by default I want the graphs to display with group by Name (name of cloud accounts)?

**Comment by gluckzhang** [comment]
Hi @Alok650, you mean setting the default group by to something else rather than `None` right? 

<img width="652" alt="image" src="https://github.com/electrolux-oss/infrawallet/assets/6386131/e05f0a75-bed3-43e4-b8d0-5db5d53946a1">

We will consider adding a plugin settings page where you can change some default values, such as this one :)

**Comment by jjwedemyer** [comment]
Would you also think about a config value in the app config that can serve as an instance default?

**Comment by gluckzhang** [comment]
> Would you also think about a config value in the app config that can serve as an instance default?

Hi @jjwedemyer, sorry but I missed this comment. Do you mean the configuring default view in the app config? I am not sure if I get the meaning of `instance default`.

**Comment by jjwedemyer** [comment]
Hi @gluckzhang,

sorry I was unclear.
I meant introducing either a built-time configuration or a key in the `app-config.yaml` setting this behavior in the way the owner wants it to.
"Instance default" is referring to default settings set by the owner/operator/organization in contrast to user settings which are set by the different users and are not shared.

**Comment by gluckzhang** [comment]
@jjwedemyer aha, now I understand it better, thanks for the explanation! I very much agree with you about having both configurations by a user and default configurations by a site admin. I think I will first enable some configurations in `app-config.yaml` as they act as default ones. Later on, we will see how to provide UI for users to have their own customization :)

**Comment by gluckzhang** [comment]
Hi @Alok650 and @jjwedemyer, FYI, in https://github.com/electrolux-oss/infrawallet/releases/tag/v0.1.8 we have added some configurations for the default view.

Later on, we are going to introduce the `wallet` idea that enables users to create their wallets (like a view with separate filters, default group by, query period, etc.). I am closing this issue for now :)
