### ISSUE TITLE
Using IAM roles instead of User

### ISSUE THREAD

**Issue by Alok650** [electrolux-oss/infrawallet#2]
Hi
Is it possible to provide IAM roles across different accounts (configured with cross account assume role) and fetch cost explorer metrics using these IAM roles. That would make it much simpler and easy to use. For implementation around that, you can refer to  https://github.com/awslabs/backstage-plugins-for-aws in which plugins like ecs make use of IAM roles. 

Interested to use this plugin!

**Comment by gluckzhang** [comment]
Hi @Alok650, thank you for your interest :)

This is in our roadmap and we are actually working on it. Will do a PR this week together with some more documentation to make IAM user optional 😀

**Comment by gluckzhang** [comment]
The changes have been merged and IAM user credentials become optional in `@electrolux-oss/plugin-infrawallet-backend:0.1.1`. You can check more information in the [README](https://github.com/electrolux-oss/infrawallet#aws) file :)

https://www.npmjs.com/package/@electrolux-oss/plugin-infrawallet-backend/v/0.1.1
