### ISSUE TITLE
Use raw numbers in the exported CSV file from cost table

### ISSUE THREAD

**Issue by gluckzhang** [electrolux-oss/infrawallet#37]
Currently if one exports the costs to CSV from the InfraWallet cost table, all the numbers have the same format and become strings. It would be better to use raw numbers to make Excel visualizations/functions easier.

<img width="524" alt="image" src="https://github.com/electrolux-oss/infrawallet/assets/6386131/1681ca07-3890-4385-8984-313f0f50afc1">

**Comment by jonathan-arenas-edo** [comment]
Hi @gluckzhang, Could you configure a GCP provider? where do you have the dataset? in US or EU?
On my ticket #38 , the system detect me a US, but my dataset is on EU, but I don't know how to configure Europe.

Kind regards.
