### ISSUE TITLE
GCP Cloud Services error Location EU

### ISSUE THREAD

**Issue by jonathan-arenas-edo** [electrolux-oss/infrawallet#38]
Hi, I'm installing this new super plugins for GCP, but I'm blocked :(
I followed all the instructions, but when I pull it up inside my GKE, I get an error that my dataset cannot be found in the US, but it is not here, is in the EU
![Captura de pantalla 2024-07-10 a las 20 42 05](https://github.com/electrolux-oss/infrawallet/assets/118807917/e275cc9f-c86b-4bea-8968-64eb818c6fe6)
.

I don't see any config parameter that has to pass the EU location.

Can anyone help me? Thank you.

**Comment by gluckzhang** [comment]
Hi @jonathan-arenas-edo, thank you for reporting this. Indeed, it seems that we hardcoded the location to `US` in the current version. I will fix it maybe by today and get back to you :)

**Comment by jonathan-arenas-edo** [comment]
thank you so much @gluckzhang :)

**Comment by gluckzhang** [comment]
The fix has been released in https://github.com/electrolux-oss/infrawallet/releases/tag/v0.1.6, could you try with `@electrolux-oss/plugin-infrawallet-backend:0.1.6` and see if it works?

**Comment by jonathan-arenas-edo** [comment]
Hi @gluckzhang thank you! I will test asap and I will give you my feedback!

**Comment by gluckzhang** [comment]
Perfect, thanks! By the way, I will remove your comment on another issue that is not related to this location bug. Let's keep all the discussions about this error under the same thread :)

**Comment by jonathan-arenas-edo** [comment]
Ok, perfect! Is working on EU. Many thanks.

Last question, Is it possible to view the cost en €?

<img width="1249" alt="image" src="https://github.com/electrolux-oss/infrawallet/assets/118807917/586bee64-2bbc-41c2-8920-f8e33825556f">

**Comment by gluckzhang** [comment]
Great it works! Unfortunately it does not support custom currencies yet, and because we have costs from several cloud providers, we always keep them using the same currency (USD).

It is on our roadmap to support selecting a different currency, I am just unsure about when it will be delivered yet :)

**Comment by jonathan-arenas-edo** [comment]
Ok, I'll keep an eye on the updates.
Thank you very much for your help. It is a very interesting plugin, congratulations.

**Comment by gluckzhang** [comment]
You are welcome. Thanks again for the feedback! @jonathan-arenas-edo
