### ISSUE TITLE
AWS authentication based on env vars, setting region and support for Linked Accounts

### ISSUE THREAD

**Issue by elisiariocouto** [electrolux-oss/infrawallet#98]
Hello everyone, just stumbled upon this awesome-looking plugin in Backstage's Plugin list. I have a couple of questions:
1. I see that is required a role name for AWS but locally and on ECS (where my Backstage instance lives) we tend to use environment variables to set all the AWS auth information. Is there support for this? Is the region hardcoded to `us-east-1` or am I missing something?
2.  Does the plugin support Linked Accounts with AWS?

Happy to contribute to this project, just making sure that I'm not missing anything.

Keep up the good work!
Elisiário Couto

**Comment by emillg** [comment]
@elisiariocouto InfraWallet uses temporary security credentials to access AWS, which is done via [assume a role](https://docs.aws.amazon.com/sdkref/latest/guide/access-assume-role.html). And `us-east-1` is the region being used when assuming the role. You backstage can be hosted in any AWS region.

What info do you have today in your environment variables?

If you set up integration with an AWS account that has linked accounts, all linked accounts will be discovered automatically by InfraWallet, so you don't need to set up integration for every AWS account.

**Comment by gluckzhang** [comment]
Hi @elisiariocouto, thanks for the comment! InfraWallet's AWS client is built using the AWS SDK for JavaScript. It follows the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/setting-credentials-node.html#credchain) if `accessKeyId` and `accessKeySecret` are not provided in the config yaml file.

So this means it is possible to set up the authentication via environment variables if it is one of the approaches in that chain. I think it is also possible to rely on [ECS task IAM role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) but I have not tested it yet.

**Comment by elisiariocouto** [comment]
Hello @gluckzhang and @emillg, thank you for your responses.

Locally I use AWS profiles in my ~/.aws/config. Usually I set the profile via env vars like so:
```
AWS_DEFAULT_PROFILE=<profilename>
AWS_PROFILE=<profilename>
AWS_EB_PROFILE=<profilename>
AWS_PROFILE_REGION=<region>
```

Looking at https://github.com/electrolux-oss/infrawallet/blob/main/plugins/infrawallet-backend/src/cost-clients/AwsClient.ts#L62, it seems that the client is not following the default credential provider chain and always tries to assume roles based on the config and always sets the region to `us-east-1`. I manually edited the plugin and removed the STS call and changed the region in the code as well and it works.

With this edit, I believe that it would work if I deploy it to ECS since the ECS task IAM role is defined via environment variables if I'm not mistaken.

I think the role name should be an optional field and the region should be in the config as well. Do you agree?

On the linked accounts part, I'm not seeing any linked accounts, only the "parent" one but I will troubleshoot this further.

**Comment by gluckzhang** [comment]
@elisiariocouto aha, thanks for the explanations, now I see the full picture! OK, indeed InfraWallet always assumes a role, either based on the provided IAM user secrets, or some other tokens like an EKS service account. It makes sense to make IAM role optional since users may directly use some secrets which are supported by the library as well.

I will do more test and try to make a PR for this. Will get back to you later :)

**Comment by elisiariocouto** [comment]
On the linked accounts part, it is working perfectly, I was using the wrong account for this.

I’m working on the support for the default AWS credentials loader, I can open a PR with this :)

**Comment by gluckzhang** [comment]
> I’m working on the support for the default AWS credentials loader, I can open a PR with this :)

That would be super nice. Thank you @elisiariocouto in advance!

**Comment by elisiariocouto** [comment]
Closing this since the PR that fixes this is merged. Thank you all

**Comment by darylgraham** [comment]
@gluckzhang Do you know when this change will be released? It is a blocker for us.

**Comment by emillg** [comment]
@darylgraham We will release a new version this week. If you want to try it earlier, you can also use the release candidate version `0.1.12-20241025145127-79b0677` today from NPM.

**Comment by emillg** [comment]
@darylgraham We have now release `v0.2.0`

**Comment by darylgraham** [comment]
Wonderful thanks @emillg
